---
repos:
  - repo: local
    hooks:
      - id: autoflake
        name: Remove unused variables and imports
        entry: bash -c 'autoflake "$@"; git add -u' --
        language: python
        args:
          [
            --in-place,
            --remove-all-unused-imports,
            --remove-unused-variables,
            --expand-star-imports,
            --ignore-init-module-imports
          ]
        files: \.py$
      - id: isort
        name: Sorting import statements
        entry: bash -c 'isort "$@"; git add -u' --
        language: python
        args: [--filter-files]
        files: \.py$
      - id: black
        name: Black Python code formatting
        entry: bash -c 'black "$@"; git add -u' --
        language: python
        types: [python]
        args: [--line-length=120]
      - id: nbstripout
        name: Stripping Jupyter notebooks
        entry: bash -c 'nbstripout "$@"; git add -u' --
        language: python
        types: [jupyter]
        files: \.ipynb$
        args: ['']

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.21.0     # or higher tag
    hooks:
      - id: yamllint
        name: YAML Validator
        files: .*\.(yaml|yml)
#        args: [--format]
#    args: [--format, parsable]
