name: Sphinx Documentation

on:
  push:
    branches:    
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Create soft link
      run: |
        pwd
        ln -s src funwavetvdtools
        ls
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "sphinx/"
        build-command: "make html"
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: "docs/html"
          
