name: Update Version
on:
  push:
jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
        shell: bash
      - run: echo $(ls)
        shell: bash
      - run: sh /home/runner/work/FUNWAVE-TVD-Python-Tools/FUNWAVE-TVD-Python-Tools/.verifyVersion.sh
        shell: bash


