name: Update Version
on:
  push:
jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: pwd
        shell: bash
      - run: ls -la ..
        shell: bash
      - run: bash .verifyVersion.sh
        shell: bash


