name: Update Version
on:
  push:
jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
        shell: bash
      - run: echo $(ls)
        shell: bash
      - run: bash .verifyVersion.sh
        shell: bash


